# Generated by Django 4.2.22 on 2025-06-11 21:55

from django.db import migrations, models
import django_summernote.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', django_summernote.fields.SummernoteTextField()),
                ('section', models.CharField(choices=[('instructors', 'Our Team'), ('services', 'Services'), ('prices', 'Prices')], default='services', max_length=20)),
                ('publish', models.BooleanField(default=True)),
            ],
        ),
    ]
