# Generated by Django 4.2.22 on 2025-06-11 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='content',
            field=models.TextField(),
        ),
    ]
