# Generated by Django 4.2.22 on 2025-06-12 13:38

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_contentblock_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentblock',
            name='block_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
