# Generated by Django 4.2.22 on 2025-06-12 16:13

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contentblock_block_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='block_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
